DWALocalPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.01
  min_vel_y: 0.0
  max_vel_y: 0.0
  max_vel_theta: 1.5
  meter_scoring: true
  min_in_place_vel_theta: 0.01
  pub_traj_pc: true
  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  pdist_scale: 5.0
  gdist_scale: 0.2
  heading_lookahead: 2
  occdist_scale: 0.05
  vx_samples: 20
  
 

  holonomic_robot: false
  
