shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2
meter_scoring: true

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"
